### ISSUE TITLE
开始封号了，请大家先别用了

### ISSUE THREAD

**Issue by leslieyin** [JunzhouLiu/BILIBILI-HELPER#315]
您好，您的账号因异常数据行为，封禁7天，封禁期间将无法使用投稿、评论、弹幕、私信、投币、标签、关注、收藏等社区功能。账号封禁时间满后，您的账号将解除封禁。请自觉遵守国家相关法律法规及《社区规则》，良好的社区氛围需要大家一起维护。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by wysnxzm** [comment]
账号安全通知
系统检测到您的账号有异常使用，建议及时更改密码，确保账号安全。
若有使用第三方工具，请立即停止使用。
恶意使用第三方工具造成数据安全问题，将导致账号封停。

**Comment by JunzhouLiu** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/313#issuecomment-773947440

**Comment by yuan6975** [comment]
2.5 同样收到了系统提醒

**Comment by cyb233** [comment]
设置actions→AUTO_TASK_FOR_BILIBILI→disable workflow可以关闭自动执行吗？ @JunzhouLiu

**Comment by JunzhouLiu** [comment]
> actions→AUTO_TASK_FOR_BILIBILI→disable workflow可以关闭自动执行吗？ @JunzhouLiu

可以的。

**Comment by qeqeq1** [comment]
在2.5 15:15被警告一次，目前没什么问题 b站后台未显示异地登录，初步判断是某些特征被识别

**Comment by MikeoPerfect** [comment]
貌似又可以了

**Comment by ZeroMah** [comment]
action可以通过增加一个秘钥的方式  "skipDailyTask": false or true
的方式来选择开关任务吗

**Comment by JunzhouLiu** [comment]
config.json配置即可
    	
    	Get Outlook for iOS
    
  
 From: U_GOLD <notifications@github.com>Sent: Saturday, February 13, 2021 02:55To: JunzhouLiu/BILIBILI-HELPERCc: Junzhou Liu; MentionSubject: Re: [JunzhouLiu/BILIBILI-HELPER] 开始封号了，请大家先别用了 (#315) 

action可以通过增加一个秘钥的方式  "skipDailyTask": false or true

的方式来选择开关任务吗



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/315#issuecomment-778384652",

"url": "https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/315#issuecomment-778384652",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
