### ISSUE TITLE
更改方糖API

### ISSUE THREAD

**Issue by justin-eng** [JunzhouLiu/BILIBILI-HELPER#351]
方糖将于4月底下线SCU API.
转到新的SCT.
希望能更改API
http://sc.ftqq.com/

**Comment by JunzhouLiu** [comment]
新api已经合并至主分支，预计3月底启用，届时只需要更新serverpushkey值即可。
    	
    	Get Outlook for iOS
    
  
 From: justin-eng <notifications@github.com>Sent: Saturday, February 20, 2021 00:29To: JunzhouLiu/BILIBILI-HELPERCc: SubscribedSubject: [JunzhouLiu/BILIBILI-HELPER] 更改方糖API (#351) 

方糖将于4月底下线SCU API.

转到新的SCT.

希望能更改API

http://sc.ftqq.com/



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/351",

"url": "https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/351",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by JunzhouLiu** [comment]
已支持Turbo版server酱，无需配置新的`Secrets`,只需将`SERVERPUSHKEY`的值为Turbo版本的Key即可。
